version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - raspberrypi-db-server
      - mqtt
      - home-automation-service
      - home-automation-ui
    volumes:
      - ${CONF_PATH}:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  raspberrypi-db-server:
    container_name: raspberrypi-db-server
    image: shiviraj/raspberrypi-db-server
    restart: always
    volumes:
      - ${DB_PATH}:/app/dist/db
    environment:
      - AUTH=${DATABASE_AUTH}
    ports:
      - 27017:27017

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ${MQTT_PATH}/config:/mosquitto/config
      - ${MQTT_PATH}/data:/mosquitto/data
      - ${MQTT_PATH}/log:/mosquitto/log
    ports:
      - 1883:1883

  home-automation-ui:
    image: shiviraj/home-automation-ui
    container_name: home-automation-ui
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - home-automation-service

  home-automation-service:
    image: shiviraj/home-automation-service
    container_name: home-automation-service
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - MQTT_URL=http://mqtt
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    ports:
      - 3001:3001
    links:
      - raspberrypi-db-server
    depends_on:
      - raspberrypi-db-server
      - mqtt
