version: '3.7'

volumes:
  db:
    name: db

services:
  raspberrypi-db-server:
    container_name: raspberrypi-db-server
    image: shiviraj/raspberrypi-db-server
    volumes:
      - db:/app/dist/db
    environment:
      - AUTH=${DATABASE_AUTH}
    ports:
      - 27017:27017

  home-automation-ui:
    image: shiviraj/home-automation-ui
    container_name: home-automation-ui
    environment:
      - BFF_URL=https://home-automation-bff:3001
    ports:
      - 3000:3000
    depends_on:
      - home-automation-bff
    links:
      - home-automation-bff

  home-automation-service:
    image: shiviraj/home-automation-service
    container_name: home-automation-service
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
    ports:
      - 8080:8080
    links:
      - raspberrypi-db-server
    depends_on:
      - raspberrypi-db-server

  home-automation-bff:
    image: shiviraj/home-automation-bff
    container_name: home-automation-bff
    environment:
      - BACKEND_URL=http://home-automation-service:8080
    ports:
      - 3001:3001
    links:
      - home-automation-service
    depends_on:
      - home-automation-service


